version: '3'

services:
  etcd:
    image: soyking/etcd-goreman:3.2.7
    ports:
      - "2379:2379"
    environment:
      - CLIENT_ADDR=etcd
  e3w:
    build: .
    image: i.ti-link.com.cn:5001/lky/e3w:v1
    volumes:
      - ./conf/config.default.ini:/app/conf/config.default.ini
    ports:
      - "8080:8080"
    depends_on:
      - etcd
